apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-config
  namespace: transactbank
  labels:
    app: ${APP_NAME}
    environment: ${ENVIRONMENT}
data:
  FLASK_ENV: "${ENVIRONMENT}"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "*"
  REDIS_URL: "redis://redis:6379/0"
